#!/usr/bin/env bash
# Transfers a file from our client to a server.
argc=("$#")
argv=("$@")

if [[ $# < 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATH_TO_FILE="${argv[0]}"
	IP="${argv[1]}"
	USERNAME="${argv[2]}"
	if [[ $# -ge 4 ]]
	then
		PATH_TO_SSH_KEY="${argv[3]}"
		scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY"\
			"$PATH_TO_FILE" "$USERNAME@$IP":~/
	else
		scp -o StrictHostKeyChecking=no "$PATH_TO_FILE"\
		       	"$USERNAME@$IP":~/
	fi
fi
