#!/usr/bin/env bash
# Comment to tell you what this task it about - NOT!
sudo touch /var/run/myscript.pid
sudo bash -c "echo $$ > /var/run/myscript.pid"
#sudo bash -c "echo '$(pgrep -f 'bash ./100-process_and_pid_file')' > /var/run/myscript.pid"
#pid="echo '$(pgrep -f 'bash ./100-process_and_pid_file')'"
#echo $pid
#echo $$
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && sudo rm "/var/run/holbertonscript.pid" && exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm "/var/run/myscript.pid"' SIGQUIT
#trap "exit" SIGTERM
#trap "kill '$(pgrep -f 'bash ./100-process_and_pid_file')'" SIGQUIT
done